### ISSUE TITLE
How to reset the poll?

### ISSUE THREAD

**Issue by kenken023** [WrathChaos/react-native-poll#1]
I need to reset the poll after the user selected an option.

**Comment by kuraydev** [comment]
Hello @kenken023,
Thank you for reaching me and using this library.
Actually, you can simply put the logic for `choices` prop. Set your `choices` state to the initial choices array and when you need to reset the poll, simply set the `choices` state array with the initial choices again and set the `hasBeenVoted` prop to `false`.

**Comment by kenken023** [comment]
Thanks, it is working now! Cheers!
