### ISSUE TITLE
Store Poll Question/Title

### ISSUE THREAD

**Issue by angelinatquach** [WrathChaos/react-native-poll#12]
Would be great to add the poll Title as a prop to RNPoll, so that it is stored and rendered as one unit.

Example: 
<img width="538" alt="Screenshot 2023-09-10 at 6 53 55 AM" src="https://github.com/WrathChaos/react-native-poll/assets/21033346/7aab1625-1030-46b4-a1ad-015d03828836">

**Comment by kuraydev** [comment]
Hello @angelinatquach 

Thank you so much for using the library and requesting a feature. 

Actually, it will be a bit hard to suit every design just for a title. Since it is extremely easy to do, I think it is better to leave the devs for creating their own design solution for title
