### ISSUE TITLE
pollContainerStyle

### ISSUE THREAD

**Issue by Vikraantnegi** [WrathChaos/react-native-poll#3]
I am afraid to say this but the styling isn't really happening. The styles we are giving, isn't really going anywhere. Would you mind to see into this, and maybe use it yourself once and then put it in the example? In the example, I couldn't find pollContainerStyle attribute

**Comment by kuraydev** [comment]
@Vikraantnegi You can simply clone the project and set pollContainerStyle into the example one. It works. Can you please share the reproducible code with me? Are you sure that you're using the latest version?

**Comment by kuraydev** [comment]
@Vikraantnegi Still waiting your response :)

**Comment by Vikraantnegi** [comment]
Haven't really looked into it. Will check.

**Comment by kuraydev** [comment]
@Vikraantnegi does it work for you?
