### ISSUE TITLE
Text styling and changing highlight color for poll options

### ISSUE THREAD

**Issue by vighnesh1987** [WrathChaos/react-native-poll#6]
Hello there, is there a way to change text styling and highlight color for poll options? If not, can you please give me code pointers on how to implement that? Happy to consider putting up a PR, if you can be quick to merge it!

**Comment by kuraydev** [comment]
Hello @vighnesh1987 
Let me quick check how can we do this :) 
I will inform you today

**Comment by kuraydev** [comment]
Oke, for text styling;

`choiceTextStyle` and `percentageTextStyle`

you can customize any text style with these props. 

for highlight colour: 

`fillBackgroundColor` prop is here for customization for the filling of the colour.

If these props will not help you, please describe me with details :)
