### ISSUE TITLE
Android border-radius problem

### ISSUE THREAD

**Issue by mmaass** [WrathChaos/react-native-poll#7]
Hi,

first things first: great component 🤘🏽

I found a graphical bug on Android. The iPhone simulator does not have the issue.

<img src="https://user-images.githubusercontent.com/576477/169038217-27636a35-68ea-4ebf-add1-27b490abcb41.png" width="300" />

So the borderRadius of the Animated.View appears to be different than that of the PollItemContainer, as far as i can see.

**Comment by kuraydev** [comment]
Woa :O Never seen it. Thank you for reporting this @mmaass :) 

I'm going to fix it ASAP :) Probably going to upgrade to code as well

**Comment by SiDDhartharG** [comment]
is this fixed??
Still facing issue
        "react-native-poll": "^0.1.2"

**Comment by kuraydev** [comment]
Hello @mmaass and @SiDDhartharG 

I finally fixes this bug :) Also, added some new props and typescript errors

Here is version 1 
https://github.com/WrathChaos/react-native-poll/releases/tag/1.0.0

Please take a look at this :) 

![CleanShot 2023-07-10 at 10 30 20](https://github.com/WrathChaos/react-native-poll/assets/6813862/1a90c139-cafc-407e-994c-52b60ad46679)

**Comment by mmaass** [comment]
can confirm it's fixed in 1.0.0 👍🏼
