### ISSUE TITLE
cannot assign to read only property 'votes' of object 

### ISSUE THREAD

**Issue by zubyrbutt** [WrathChaos/react-native-poll#8]
After clicking  to a single vote
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-26 at 13 13 11](https://user-images.githubusercontent.com/29346495/170447454-ff697cf2-c686-4670-8fdf-a46c170b5e75.png)

**Comment by kuraydev** [comment]
Hello @zubyrbutt 
Thank you for reporting this, I will take a look at it ASAP

**Comment by zubyrbutt** [comment]
> Hello @zubyrbutt Thank you for reporting this, I will take a look at it ASAP

@WrathChaos Thanks for the quick response 

issue resolved when GraphQL response reformat with simple javascript function

`  const formattedChoices = choices.map((choice) => {
    return {
      id: choice.id,
      choice: choice.choice,
      votes: choice.votes,
    }
  })
`

**Comment by kuraydev** [comment]
Glad to hear that :) Please open an issue if you need anything else and have an idea to improve the library :)
